name: proyectofinal
description: App de Gastos Personales - Neon Futurista
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.1.0
  google_fonts: ^5.0.0
  fl_chart: ^0.68.0
  animations: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.3
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true